#!/usr/bin/env sh

c() { bspc config "$@" &  }
r() { bspc rule -a "$@" & }

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

#################################################################
# BSPWM Configuration
#################################################################

c window_gap                20 
c border_width         	    2 

#----------------
#LAYOUTS
c split_ratio               0.50

#MONOCLE LAYOUT (FULLSCREEN)
c borderless_monocle   	    true  
c gapless_monocle           false 
c single_monocle	    false 

#-----------------
c focus_follows_pointer     true

# Border
c focused_border_color      "#6c71c4"
c normal_border_color       "#073642"
c active_border_color       "#073642"

#################################################################
# Window Rules 
#################################################################

r Pavucontrol state=floating
r Screenkey state=floating center=on
r Protonvpn state=floating center=on
r Nitrogen state=floating center=on
r Galculator state=floating
r Yad state=floating

#################################################################
# Autostarting 
#################################################################

# Polybar 
~/.config/polybar/launch.sh &

# Dunst 
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
nitrogen --restore &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &

# Picom
picom -b --experimental-backend &

# Network Applet
nm-applet --indicator &

# Fix cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

#Clipmenu
clipmenud &

#enabling num lock on login
numlockx &

#start clipmenu daemon
clipmenud &

xrdb -merge ~/.Xresources
