#! /bin/sh

c() { bspc config "$@" &  }
r() { bspc rule -a "$@" & }

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

c border_width         2 
c window_gap           8 

c split_ratio          0.52
c borderless_monocle   true
c gapless_monocle      true
c focus_follows_pointer true

r Gimp desktop='^8' state=floating follow=on
r mplayer2 state=floating
r Yad state=floating
r Kupfer.py focus=on
r Screenkey manage=off
r Pavucontrol state=floating
r Protonvpn state=floating

r Nitrogen state=floating
r Galculator state=floating

# Border
c focused_border_color        "#6c71c4"
c normal_border_color         "#073642"
c active_border_color         "#073642"

# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# Bar
~/.config/polybar/launch.sh &

# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
nitrogen --restore &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &

# Picom
picom -b --experimental-backends &

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

#Clipmenu
clipmenud &

#enabling num lock on login
numlockx &

#start clipmenu daemon
clipmenud &

xrdb -merge ~/.Xresources
