#!/usr/bin/env bash 


# ____ ____ ____ ____ ____ 
#||b |||s |||p |||w |||m ||
#||__|||__|||__|||__|||__||
#|/__\|/__\|/__\|/__\|/__\|
#


pgrep -x sxhkd > /dev/null || /usr/bin/sxhkd &

bspc rule -r "*"

config() { bspc config "$@" ; }
rule() { bspc rule -a "$@" ; }
_() { pgrep -x "$1" > /dev/null || "$@" & }


#----------------------
# Configure monitors

#bspc monitor -d I II III IV V VI VII VIII IX X

export MONITOR=$(xrandr -q | grep primary | cut -d' ' -f1)
export MONITORS=( $(xrandr -q | grep ' connected' | cut -d' ' -f1) )
MONITOR=${MONITOR:-${MONITORS[0]}}

# Only have workspaces for primary monitor
for monitor in $MONITORS; do
  bspc monitor $monitor -d {0,1,2,3,4,5,6} 
done
bspc monitor $MONITOR -d {0,1,2,3,4,5,6,7,8,9}

config remove_disabled_monitors  true
config remove_unplugged_monitors true

################################################################# 
# BSPWM Configuration 
#################################################################

config window_gap                14 
config border_width         	  2 

#----------------
# Layouts
config split_ratio               0.50

# Monocle Layout (FULLSCREEN)
config borderless_monocle   	 true
config gapless_monocle           true
config single_monocle	    	 false

#-----------------
config focus_follows_pointer     true
config pointer_follows_focus     false

config normal_border_color       "#32334E"
config focused_border_color      "#B6D0FD"
#config active_border_color       "#96A5A9"
config active_border_color       "#3C4044"
config presel_feedback_color     "#7A7C8C"

#-----------------
# Padding
config top_monocle_padding		 0
config bottom_monocle_padding    0
config right_monocle_padding	 0 
config left_monocle_padding 	 0

notify-send "bspc configs set"


#################################################################
# Window Rules 
#################################################################

rule Pavucontrol state=floating center=on
rule Screenkey state=floating center=on manage=on
rule Protonvpn state=floating center=on
rule Nitrogen state=floating center=on
rule Gpick state=floating center=on manage=on
rule gnome-calculator state=floating focus=on center=on
rule Yad state=floating
rule File-roller state=floating manage=on
rule firefox:Places:Library state=floating center=on
rule discord focus=off desktop=^3
rule Zathura state=tiled

notify-send "bspc rules set"

#----------------
# X tweaks 

if [ $(xset -q | grep "auto repeat delay" | awk '{print $4}') -ne 400 ]; then
    sleep 0.5
    xset r rate 400 30 &
fi
xsetroot -cursor_name left_ptr &
numlockx on &


#################################################################
# Autostarting 
#################################################################

# Raise polybar
$HOME/.config/polybar/launch.sh &

$HOME/.config/bspwm/scripts/low_bat_notifier.sh &

dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &

nitrogen --restore &

# Initiate policy-kit 
_ /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

_ picom -b --experimental-backends

_ nm-applet --indicator

_ dunst

_ clipmenud

# Handle device mounts
_ udiskie

notify-send "bg apps started"

xrdb -merge "${HOME}/.Xresources"

notify-send "all done"
