#!/usr/bin/env bash 

# ____ ____ ____ ____ ____ 
#||b |||s |||p |||w |||m ||
#||__|||__|||__|||__|||__||
#|/__\|/__\|/__\|/__\|/__\|
#

config() { bspc config "$@" ; }
rule() { bspc rule -a "$@" ; }
run() { pgrep -x "$1" > /dev/null || "$@" & }

pgrep -x sxhkd > /dev/null || /usr/bin/sxhkd &
bspc rule -r "*"

#--------------------------------------------
# Configure monitors

MONITOR=$(xrandr -q | grep primary | cut -d ' ' -f1)
MONITORS=$(xrandr -q | grep ' connected' | cut -d ' ' -f1)
MONITOR=${MONITOR:-${MONITORS[0]}}

# Only have workspaces for primary monitor
for monitor in $MONITORS; do
  bspc monitor "$monitor" -d {0,1,2,3,4,5,6} 
done
bspc monitor "$MONITOR" -d {0,1,2,3,4,5,6,7}

config remove_disabled_monitors  true
config remove_unplugged_monitors true

#--------------------------------------------
# Window configs

config window_gap                12
config border_width              2 
config ignore_ewmh_focus         false 

#----------------
# Layouts
config split_ratio               0.50

# Monocle Layout (FULLSCREEN)
config borderless_monocle        true
config gapless_monocle           true
config single_monocle            false

config focus_follows_pointer     true
config pointer_follows_focus     false

config normal_border_color       "#0F0F0F"
config focused_border_color      "#555555"
config active_border_color       "#3C4044"
config presel_feedback_color     "#7A7C8C"

# Padding
config top_monocle_padding       0
config bottom_monocle_padding    0
config right_monocle_padding     0 
config left_monocle_padding      0

notify-send "Configs set"


#--------------------------------------------
# Rules

rule Pavucontrol state=floating center=on
rule Screenkey state=floating center=on manage=on
rule Protonvpn state=floating center=on
rule Nitrogen state=floating center=on
rule Gpick state=floating center=on manage=on
rule gnome-calculator state=floating focus=on center=on
rule Yad state=floating
rule File-roller state=floating manage=on
rule firefox:Places:Library state=floating center=on
rule discord focus=off desktop=^3
rule Zathura state=tiled
rule smile state=floating manage=on

notify-send "Rules set"

#--------------------------------------------
# X tweaks 

xsetroot -cursor_name left_ptr &
numlockx on &

#--------------------------------------------
# Autostarting 

~/.config/polybar/launch.sh & # Raise polybar
~/.scripts/lowbattery &
~/.fehbg &
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
run /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 # Initiate policy-kit 
run picom -b --experimental-backends
run nm-applet --indicator
run dunst
run clipmenud
run udiskie # Handle device mounts

notify-send "BG Apps started"

xrdb -merge "${HOME}/.Xresources"

notify-send "WM Started!"

