#!/usr/bin/env bash

if [ ! -e /tmp/pbtg ]; then
    touch /tmp/pbtg
    polybar-msg cmd hide 
    bspc config top_padding 0
    bspc config bottom_padding 0
    bspc config top_monocle_padding 8
    bspc config bottom_monocle_padding 8
    bspc config left_monocle_padding 8
    bspc config right_monocle_padding 8 
else
    rm /tmp/pbtg
    polybar-msg cmd show 
    bspc config top_monocle_padding 0
    bspc config bottom_monocle_padding 0
    bspc config left_monocle_padding 0
    bspc config right_monocle_padding 0
fi
