#!/usr/bin/env bash
#
# scryy - screen yank!
# (c) Shree Kottes
#

addshadow() {
    convert "${1}.png" \( +clone -background black15 -shadow 80x40+5+30 \) +swap -background transparent -layers merge +repage "${1}-XD.png" 
}

file="/tmp/$(date +"%Y%m%d-%H%M%S")"
cords=$(slop)

if [ $? -ne 0 ]; then
    notify-send "slop cancelled."
    exit 1;
fi

maim -u -o -g ${cords} ${file}.png
addshadow $file 
notify-send "screen captured!"
xclip -selection clipboard -t image/png -i ${file}-XD.png
dragon-drop -x ${file}-XD.png
#xclip -selection clipboard -t image/png -i ${file}.png

