#!/usr/bin/env bash
#screenshot_clip.sh
p="/tmp/$(date +"%d-%m-%y-%M").png"

maim -u -o -s $p

add-shadow $p

xclip -selection clipboard -target image/png -i $p-shadow.png
notify-send "Screenshot copied to clipboard!"
