#!/usr/bin/env bash
#
# sstool - take a screenshot
# (c) Shree Kottes
#

option=$(echo -e "screen\nwindow\narea" | rofi -dmenu -font "Input Mono 12")
case $option in
    window | area)
        coords=$(slop)
        if [ $? -ne 0 ]
        then
            notify-send "select cancelled!"
            exit 1
        fi
        sleep 0.5
        maim -g $coords -u ~/pics/ss/$(date +"%Y%m%d-%H%M%S").png
    ;;
    screen)
        sleep 0.5
        maim ~/pics/ss/$(date +"%Y%m%d-%H%M%S").png
    ;;
    *) ;;
esac

if [ $? -eq 0 ]
then
    notify-send "ss captured."
fi

